version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432

  webapp:
    build: .
    restart: always
    links:
      - postgres:postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432
      - TELEGRAM_TOKEN=8084004206:AAGW1DR2_0atsaTdBzE5jEFWax9GtFZ9Uog

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450